development:
  adapter: postgresql
  url: limestone

test:
  adapter: postgres
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>

staging:
  adapter: postgres
  url: <%= ENV['DATABASE_URL'].gsub('?', '_staging?') %>

production:
  adapter: postgres
  url: <%= ENV['DATABASE_URL'].gsub('?', '_production') %>
