development:
  admin_first_name: Joshua
  admin_last_name: Flark
  admin_email: joshuajmark@gmail.com
  admin_password: password
  domain_name: localhost:5000
  stripe_api_key: sk_test_ucpCIBoeZDNHf3uTP1P0yBX7
  stripe_publishable_key: pk_test_5Fu6VHfInqqneIXOdMr2Gg7g
  secret_key_base: d3f7495a09fdfd9099db6e648c5c0718ef21bd7c80a2b3549c51cea0c25c942c45cfd9ed2f906f31721f245a1a8bb8288dacd45dafb7cacc72c4d71076c6a5f6

  # AWS IAM limestone-development
  aws_access_key_id: AKIAJ5CIPA5HPLH6KT5A
  aws_secret_access_key: 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
  aws_region: us-west-2
  aws_bucket: limestone-development

  trial_period: 1209600 # 14 days

test:
  secret_key_base: f60aec48ad5affb24f776e86f2826215eae919979ea27d11564b4ef8dbdac6342a9f2b33a93868a8071e112b7e1fc49fa6680d529b904a00480d8503ac444d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
